services:
  apache-hop:
    build:
      context: .
      args:
        HOP_VERSION: ${HOP_VERSION:-latest}
    ports:
      - "${HOP_WEB_PORT:-8080}:8080"
      - "${HOP_DEBUG_PORT:-5005}:5005"
    environment:
      # Environment Type (dev/prod)
      - ENV_TYPE=${ENV_TYPE:-development}
      
      # Hop Configuration
      - HOP_LOG_LEVEL=${HOP_LOG_LEVEL:-Basic}
      - HOP_RUNTIME=${HOP_RUNTIME:-local}
      - HOP_PROJECT_NAME=${HOP_PROJECT_NAME:-default-project}
      - HOP_WEB_HOST=${HOP_WEB_HOST:-0.0.0.0}
      - HOP_WEB_PORT=${HOP_WEB_PORT:-8080}
      - HOP_FILE_PATH=${HOP_FILE_PATH:-/files/pipelines/filename.hwf}
      - HOP_PROJECT_FOLDER=${HOP_PROJECT_FOLDER:-/files}
      - HOP_SHARED_JDBC_FOLDERS=${HOP_SHARED_JDBC_FOLDERS:-/files/drivers}
      - HOP_METADATA_FOLDER=/files/metadata
      - HOP_CONFIG_FOLDER=/files
      - HOP_RUN_CONFIG=${HOP_RUN_CONFIG:-local}
      - HOP_AUTO_RUN_PIPELINE=${HOP_AUTO_RUN_PIPELINE:-false}
      
      # Google Cloud Configuration
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GOOGLE_SERVICE_ACCOUNT_EMAIL=${GOOGLE_SERVICE_ACCOUNT_EMAIL}
      - GOOGLE_APPLICATION_CREDENTIALS=/home/hop/.config/gcloud/application_default_credentials.json
      
      # Java/Performance Settings
      - JAVA_OPTS=${JAVA_OPTS:--Xmx1G -XX:+UseG1GC -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Dio.netty.tryReflectionSetAccessible=false -Dio.netty.noUnsafe=true -Dio.netty.native.workdir=/tmp -Dio.netty.leakDetection.level=disabled -Dgrpc.netty.useCustomAllocator=false -Dio.netty.transport.noNative=true}
      - HOP_MAX_CHILDREN=${HOP_MAX_CHILDREN:-10}
      
      # Debug Settings (Development only)
      - HOP_DEBUG_ENABLED=${HOP_DEBUG_ENABLED:-false}
      - HOP_DEBUG_PORT=${HOP_DEBUG_PORT:-5005}
    volumes:
      - ./logs:/home/hop/logs
      - ./audit:/home/hop/audit
      # Project files
      - ./metadata:/files/metadata:${HOP_VOLUME_PERMISSIONS:-ro}
      - ./drivers:/files/drivers:${HOP_VOLUME_PERMISSIONS:-ro}
      - ./project-config.json:/files/project-config.json:${HOP_VOLUME_PERMISSIONS:-ro}
      - ./pipelines:/files/pipelines:${HOP_VOLUME_PERMISSIONS:-ro}
      # GCloud config for development (only mounted in dev)
      - ${GCLOUD_CONFIG_PATH:-~/.config/gcloud}:/home/hop/.config/gcloud:ro
      # Ensure application default credentials are available
      - ${GCLOUD_CONFIG_PATH:-~/.config/gcloud}/application_default_credentials.json:/home/hop/.config/gcloud/application_default_credentials.json:ro
    restart: ${RESTART_POLICY:-unless-stopped}
    command: [
      "/opt/hop/hop-run.sh",
      "-f", "/files/pipelines/filename.hwf",
      "-r", "direct_runner",
      "-l", "Basic"
    ]
    deploy:
      resources:
        limits:
          memory: ${HOP_MEMORY_LIMIT:-2G}
          cpus: ${HOP_CPU_LIMIT:-1.0}