version: '3.8'

services:
  hop-web:
    image: apache/hop-web:latest
    container_name: hop-web
    ports:
      - "8080:8080"
    volumes:
      - ./projects:/opt/hop/projects
      - ./scripts/init-hop.sh:/docker-entrypoint-initdb.d/init-hop.sh
    environment:
      - HOP_WEB_THEME=light
      - HOP_WEB_HOST=0.0.0.0
      - HOP_WEB_PORT=8080

  hop-setup:
    image: curlimages/curl:latest
    container_name: hop-setup
    depends_on:
      - hop-web
    volumes:
      - ./scripts/setup-hop.sh:/setup-hop.sh
    command: ["/bin/sh", "/setup-hop.sh"]